server:
  port: 8080
  servlet:
    context-path: /oauth2server
logging:
  level:
    org.springframework: debug
newbasegrid:
  security:
    oauth2:
      storeType: jwt #或者jwt
      jwtSigningKey: newbasegrid
      clients[0]:
        clientId: client1
        clientSecret: client1
        clientUrl: http://localhost:8081/client1/login
      clients[1]:
        clientId: client2
        clientSecret: client2
        clientUrl: http://localhost:8082/client2/login
spring:
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
#spring:
#  redis:
#    host: localhost
#    port: 6379
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1s
#        min-idle: 0
#        max-idle: 8