auth-server: http://localhost:8080/oauth2server # server地址
server:
  port: 8081
  servlet:
    context-path: /client1
security:
  oauth2:
    client:
      client-id: client1
      client-secret: client1
      user-authorization-uri: ${auth-server}/oauth/authorize #请求认证的地址
      access-token-uri: ${auth-server}/oauth/token #请求令牌的地址
    resource:
      jwt:
        key-uri: ${auth-server}/oauth/token_key
      user-info-uri: ${auth-server}/user/me
      token-info-uri: ${auth-server}/oauth/check_token
logging:
  level:
    org.springframework: debug
spring:
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/